# Generated by Django 3.2.4 on 2021-07-04 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='meetpups',
            new_name='Meetpup',
        ),
    ]
