# Generated by Django 3.2.4 on 2021-07-04 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_meetpups_meetpup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meetpup',
            new_name='Meetup',
        ),
    ]
